### ISSUE TITLE
node-exporter targetdown

### ISSUE THREAD

**Issue by nohant** [sighupio/fury-kubernetes-monitoring#106]
We are facing the same problem in different cluster, every single one of the has begun having this alert after the kubernetes upgrade to `1.21`, and going even to the `1.23` the alert is still there.

**error faced and symptoms**
the log of the pod are full of this: `node-exporter-gsg5p kube-rbac-proxy http: proxy error: context canceled`
prometheus see pod as down and start alerting for `targetdown:
`100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job, namespace, service)) > 10`

**module version**
the version for the monitoring is usually the v1.14.3.

**kubenertes version**
from 1.21 upwards

**test done for solution**
removed the `runasnonroot` true,
removed any limits on the resources
checked if there were throttling problems
edited `scrapeTimeout` and `interval`

**solution that has worked**
remove the container kube-rbac-proxy from the node-exporter pod

**Comment by ralgozino** [comment]
I can replicate the error in our test environment. The issue seems to be related to the `kube-rbac-proxy` container CPU limits, they are too low and the container gets throttled. This is the current configuration:

https://github.com/sighupio/fury-kubernetes-monitoring/blob/9fb37ec5f7ca919032840d0107c2c0109e1be975/katalog/node-exporter/daemonset.yaml#L84-L87 

This explains why after restarting the pod the error disappears for some minutes until the pod gets throttled again.

Raising the value for the CPU limits **for the kube-rbac-proxy` container** seems to solve the issue. Notice that is not the **node-exporter** container, the pod has more than one container.

You can see here how before the metrics were not working properly and after raising the CPU limits for the `kube-rbac-proxy` container metrics are back to normal and without issues for mode than 20 minutes:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6362698/204487868-fc319d60-7b60-4f40-a8b0-4c6a8effdcfc.png">

**Comment by nohant** [comment]
thanks @ralgozino, but we also compltely remove limits on the container for the rbac and after 30/40 minutes the problem came back as usual sadly.
We could try again in the next activity nonetheless

**Comment by ralgozino** [comment]
You are correct, started happening again in the test cluster after raising the limits.

[Upstream seems to be removing the limits](https://github.com/prometheus-operator/kube-prometheus/issues/72#issuecomment-488657258), and also OpenShift according to another comment in that thread.

We should consider removing them by default, I'll test that in the meantime.

**Comment by ralgozino** [comment]
Also in the test cluster even without setting resource limits `kube-rbac-proxy` stops responding after some time.

Needs further investigation.

**Comment by lnovara** [comment]
Could this be related to the following upstream issues?

- https://github.com/prometheus-operator/kube-prometheus/issues/1922
- https://github.com/prometheus/node_exporter/issues/2500#issuecomment-1290399604

**Comment by ralgozino** [comment]
My test cluster is based on Ubuntu 20.04 kernel `5.4.0-132-generic` with 4 CPUs.

Even though the kernel version seems not to be affected by the second issue you listed, I'm testing passing `GOMAXPROX: 1` as env var to see if that solves the issue 🤞

**Comment by ralgozino** [comment]
Almost 24h after applying ` GOMAXPROCS=1` and no signs of the error in the logs and node exporter working just fine 🎉 
<img width="1733" alt="image" src="https://user-images.githubusercontent.com/6362698/205008210-a855480f-dcfa-44eb-8e01-20684e8b9d6a.png">

I consider the PR #112 the fix to this issue.

**Comment by nohant** [comment]
really great work @ralgozino , thank you for real.
This was a real pain and now its fixed.
